version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: |
          make clean
          make test
workflows:
  version: 2
  build:
    jobs:
      - test
